### ISSUE TITLE
TypeError: Cannot read property 'pit' of undefined

### ISSUE THREAD

**Issue by jeholliday** [mortorqrobotics/MorScout#2]
```
/Users/username/Documents/SourceTree/MorScout/server/server.js:25
 = readJSON("dataPoints.json")[(entry.meta.match == "pit") ? "pit" : "match"];
                                                                     ^
TypeError: Cannot read property 'pit' of undefined
    at validEntry (/Users/username/Documents/SourceTree/MorScout/server/server.js:25:79)
    at IncomingMessage.<anonymous> (/Users/username/Documents/SourceTree/MorScout/server/server.js:172:11)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:764:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
```

**Comment by jeholliday** [comment]
I think I found the problem.  "server/dataPoints.json" needs a comma at the end of line 9.

**Comment by Farbod909** [comment]
Thank you!
