### ISSUE TITLE
Errors in command prompt when setting up server/creating an account

### ISSUE THREAD

**Issue by ConcernedMorScoutUser** [mortorqrobotics/MorScout#4]
MorScout worked fine up until a few days ago, but errors started to pop up. Redownloading, reinstalling node.js, and using a different computer has not solved it.

The error for starting the server (inputting 'node server' after navigating to the server folder):

let http = require("http");
^^^
SyntaxError: Unexpected strict mode reserved word
     at exports.runInThisContext (vm.js:7316)
     at Module._compile (module.js:443:25)
     at Object.Module._extensions..js (module.js:479:10)
     at Module.load (module.js:355:32)
     at Function.Module._load (module.js:310:12)
     at Function.Module.runMain (module.js:501:10)
     at startup (node.js:129:16)
     at node.js:814:3

Error for inputting 'node userManager':

let fs = require("fs");
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by voidpigeon** [comment]
Use node --harmony server. The --harmony option enables ECMAScript 6 stuff in node.

**Comment by voidpigeon** [comment]
Be sure to use node.js v0.12.0 to be sure it supports ECMAScript 6.
